"""
Convert trained Keras model to INT8 TensorFlow Lite and export C header.

Part 3 from requested workflow:
- INT8 quantization
- .tflite export
- model.h export for ESP32 firmware
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import tensorflow as tf


ARTIFACTS_DIR = Path("artifacts")
MODEL_PATH = ARTIFACTS_DIR / "smart_load_cnn.keras"
REP_DATA_PATH = ARTIFACTS_DIR / "representative_data.npy"
TFLITE_PATH = ARTIFACTS_DIR / "smart_load_cnn_int8.tflite"
HEADER_PATH = ARTIFACTS_DIR / "model.h"
TARGET_MAX_BYTES = 2048


def representative_data_gen(samples: np.ndarray):
    for i in range(samples.shape[0]):
        yield [samples[i : i + 1]]


def export_tflite_int8() -> bytes:
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Missing trained model: {MODEL_PATH}")
    if not REP_DATA_PATH.exists():
        raise FileNotFoundError(f"Missing representative dataset: {REP_DATA_PATH}")

    model = tf.keras.models.load_model(MODEL_PATH)
    rep_data = np.load(REP_DATA_PATH).astype(np.float32)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_data_gen(rep_data)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    TFLITE_PATH.write_bytes(tflite_model)
    return tflite_model


def write_c_header(model_bytes: bytes, path: Path, array_name: str = "g_smart_load_model_data"):
    hex_bytes = ", ".join(f"0x{b:02x}" for b in model_bytes)
    content = f"""#ifndef MODEL_H_
#define MODEL_H_

// Auto-generated by python/convert_to_tflite.py
// Format: INT8 quantized TensorFlow Lite model.

#include <cstddef>
#include <cstdint>

alignas(16) const unsigned char {array_name}[] = {{
  {hex_bytes}
}};

const unsigned int g_smart_load_model_len = {len(model_bytes)};

#endif  // MODEL_H_
"""
    path.write_text(content, encoding="utf-8")


def main():
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    model_bytes = export_tflite_int8()
    write_c_header(model_bytes, HEADER_PATH)

    size_kb = len(model_bytes) / 1024.0
    size_bytes = len(model_bytes)
    print(f"TFLite model written: {TFLITE_PATH}")
    print(f"C header written:   {HEADER_PATH}")
    print(f"Model size: {size_kb:.2f} KB ({size_bytes} bytes)")
    if size_bytes > TARGET_MAX_BYTES:
        print(f"FAIL: Model exceeds strict 2KB target ({TARGET_MAX_BYTES} bytes).")
        raise SystemExit(2)
    else:
        print("PASS: Model size is within strict 2KB target.")


if __name__ == "__main__":
    main()
