#ifndef MODEL_H_
#define MODEL_H_

// Example placeholder model.
// Replace this file with artifacts/model.h generated by:
//   python python/convert_to_tflite.py
//
// Expected symbols:
// - g_smart_load_model_data
// - g_smart_load_model_len

#include <cstddef>
#include <cstdint>

alignas(16) const unsigned char g_smart_load_model_data[] = {
    0x20, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

const unsigned int g_smart_load_model_len = sizeof(g_smart_load_model_data);

#endif  // MODEL_H_

